### PR TITLE
Change mail address and explorer

### PR DESCRIPTION
**Pull request by r000n**

### CODE REVIEW

**Comment by maaku** [comment]
I'm for using coinplorer instead. I think that should be merged separately.

But why the change to how emails are handled?

**Comment by jtimon** [comment]
The users already receive the mail from foundation@freicoin.org which I think it's what was important:

https://github.com/freicoin/foundation/commit/791ae401aa20d10e1a5ae8714f463c4167728dd6

Now it sends notifications to all superusers (@maaku and me) and also to all organization moderators (currently the 5 foundation directors). Moderators can validate/block organizations and merchants.
I kept organization and merchant moderators separated so that in the future, if there's many merchants and/or orgs registering we can delegate some of that work.

About the explorer, sorry for the pending cleanup. Django template tags aren't used anymore and the faucet is not usable.
So the only relevant part is this:

https://github.com/freicoin/foundation/blob/626fb8267ec5189d0d5559fe7f3bf6f7ae3983ac/static/js/directives/commonDirs.js#L22

I don't think your changes will work though, they will produce things like:

https://coinplorer.com/FRC/address/1LRq9qB81Rjv4tjtp8szxiw9TeGfVcZYGb
https://coinplorer.com/FRC/tx/bf35df29665af3039315d012888c0c78da0aac294d63c93894646c1896f86859

When you want is:

https://coinplorer.com/FRC/addresses/1LRq9qB81Rjv4tjtp8szxiw9TeGfVcZYGb
https://coinplorer.com/FRC/transactions/bf35df29665af3039315d012888c0c78da0aac294d63c93894646c1896f86859

Coinplorer doesn't seem to follow the address/tx 'standard' that blockexplorer.com blockchain.info or cryptocoinexplorer.com use. But it's an easy to handle special case.
I'll commit that change. It is good to test the changes before committing. 

make run

You will need to go to the admin to add categories and be able to submit orgs:

http://127.0.0.1:8000/admin/donations/category/add/

Ask if you need further help to run the website locally.

**Comment by jtimon** [comment]
Maybe we can suggest to coinplorer.com that they use tx and address like the rest too.

**Comment by r000n** [comment]
I'm suggested to keep all foundation-related things in separate mailbox.
Currently moderators = foundation members, so idea was simple.

**Pull request closed without merging**
